version: 2

project_name: logzero

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: logzero
    main: ./cmd/logzero
    binary: logzero
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

sboms:
  - artifacts: archive
    args: ["$artifact", "--output", "spdx-json=$document"]

signs:
  - artifacts: checksum
    args:
      - "sign-blob"
      - "--yes"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"

dockers:
  - image_templates:
      - "ghcr.io/pliauga/logzero:{{ .Version }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/Pliauga/logzero"
    dockerfile: Dockerfile
    goarch: amd64
  - image_templates:
      - "ghcr.io/pliauga/logzero:{{ .Version }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/Pliauga/logzero"
    dockerfile: Dockerfile
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/pliauga/logzero:{{ .Version }}"
    image_templates:
      - "ghcr.io/pliauga/logzero:{{ .Version }}-amd64"
      - "ghcr.io/pliauga/logzero:{{ .Version }}-arm64"
  - name_template: "ghcr.io/pliauga/logzero:latest"
    image_templates:
      - "ghcr.io/pliauga/logzero:{{ .Version }}-amd64"
      - "ghcr.io/pliauga/logzero:{{ .Version }}-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
